### Step 1: 	Hello, Data! Load raw CSV, display first 3 rows

1. Chatgpt was used to add new column named "ShippingAddressID" is added to the dataset and the rows are populated with a 5-digit unique numbers to be served as foreign key to another data set containing the shipping details

2. Another column named "CouponCode" is added programatically, and the rows are populated with another 5 digit random keys.

In [423]:
from importlib import reload
import random
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

import modules.FileManager
reload(modules.FileManager)

import modules.DBManager
reload(modules.DBManager)

# Path to the CSV file containing 
sales_records_path = "data/1000_sales_records_with_shipping_address_id.csv"
address_path = "data/shipping_addresses.csv"
num_of_rows_needed = 500 # As per assignment requirement says
#Loads the CSV file
fileManager = modules.FileManager.FileManager(sales_records_path, num_of_rows_needed)
sales_data = fileManager.get_data()

address_data = pd.read_csv(address_path)

# Filter addresses that match the 500 rows
filtered_addresses = address_data[
    address_data["shipping_address_id"].isin(sales_data["Shipping Address ID"])
]

# Get the number of rows in the DataFrame
num_rows = len(filtered_addresses)

db_manager = modules.DBManager.DBManager(filtered_addresses)
# db_manager._drop_and_create_table()
# db_manager._insert_into_table()
addresses_from_database = db_manager._fect_all()

# Merge sales_data with address_data on 'Shipping Address ID'
sales_shipping_data = pd.merge(sales_data, addresses_from_database, left_on='Shipping Address ID', right_on='shipping_address_id', how='inner')

# Print the first 3 rows of the data
sales_shipping_data.head(3)

✅ Successfully loaded 500 rows from data/1000_sales_records_with_shipping_address_id.csv

c:\Users\MOSTAFA\Desktop\ML Programming\Lab 2\modules\DBManager.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(sql_query, conn)

✅ Successfully loaded 500 rows from Shipping_Addresses table.

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,...,Total Cost,Total Profit,Shipping Address ID,shipping_address_id,country,street,city,state/province,postal_code,phone_number
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,...,2224085.18,1468506.02,85831,85831,Libya,1069 Main St,Sydney,ENG,33769.0,Phone Number
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,...,274426.74,190526.34,72252,72252,Canada,8872 Main St,Toronto,NY,98001.0,Phone Number
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,...,241840.14,145419.62,92369,92369,Libya,2924 Main St,Tokyo,BE,97404.0,Phone Number

### Step 2: Pick the Right Container. Justify dict vs namedtuple vs sets(1–2 sentences)

1. Dictionaries (dict): Best for mapping unique keys to values, offering fast lookups and mutable data structures for dynamic key-value pairs. 

2. Named Tuples (namedtuple): Ideal for creating lightweight, immutable objects with readable attribute names, serving as a clean and efficient alternative to a dictionary for representing a fixed set of data. 

3. Sets (set): Designed for storing unique, unordered elements, providing very fast membership testing and operations like union and intersection. 

#### In this case, Dictionary would be a better choice than namedtuple or sets

### Step 3: Implement Functions and  Data structure and use them to populate a data structure (Dictionary)


### Step 4: Bulk Loaded - Map data structures from dataframes to dictionaries

In [424]:
# Convert data into a dictionary
records_dict = sales_shipping_data.to_dict(orient="records")
print(records_dict[:3])  # Print the first 3 records to verify

[{'Region': 'Middle East and North Africa', 'Country': 'Libya', 'Item Type': 'Cosmetics', 'Sales Channel': 'Offline', 'Order Priority': 'M', 'Order Date': '10/18/2014', 'Order ID': 686800706, 'Ship Date': '10/31/2014', 'Units Sold': 8446, 'Unit Price': 437.2, 'Unit Cost': 263.33, 'Total Revenue': 3692591.2, 'Total Cost': 2224085.18, 'Total Profit': 1468506.02, 'Shipping Address ID': 85831, 'shipping_address_id': 85831, 'country': 'Libya', 'street': '1069 Main St', 'city': 'Sydney', 'state/province': 'ENG', 'postal_code': 33769.0, 'phone_number': 'Phone Number'}, {'Region': 'North America', 'Country': 'Canada', 'Item Type': 'Vegetables', 'Sales Channel': 'Online', 'Order Priority': 'M', 'Order Date': '11/7/2011', 'Order ID': 185941302, 'Ship Date': '12/8/2011', 'Units Sold': 3018, 'Unit Price': 154.06, 'Unit Cost': 90.93, 'Total Revenue': 464953.08, 'Total Cost': 274426.74, 'Total Profit': 190526.34, 'Shipping Address ID': 72252, 'shipping_address_id': 72252, 'country': 'Canada', 'street': '8872 Main St', 'city': 'Toronto', 'state/province': 'NY', 'postal_code': 98001.0, 'phone_number': 'Phone Number'}, {'Region': 'Middle East and North Africa', 'Country': 'Libya', 'Item Type': 'Baby Food', 'Sales Channel': 'Offline', 'Order Priority': 'C', 'Order Date': '10/31/2016', 'Order ID': 246222341, 'Ship Date': '12/9/2016', 'Units Sold': 1517, 'Unit Price': 255.28, 'Unit Cost': 159.42, 'Total Revenue': 387259.76, 'Total Cost': 241840.14, 'Total Profit': 145419.62, 'Shipping Address ID': 92369, 'shipping_address_id': 92369, 'country': 'Libya', 'street': '2924 Main St', 'city': 'Tokyo', 'state/province': 'BE', 'postal_code': 97404.0, 'phone_number': 'Phone Number'}]

### Step 5: Quick Profiling - Min/mean/max price, unique city count (set)

In [425]:
numerical_columns = sales_shipping_data.select_dtypes(include=np.float64)
# numerical_columns.head()

# Extract the list of countries
countries = sales_shipping_data['Country']

# Use a set to get the unique countries and count them
unique_countries_count = len(set(countries)) 

print(f"\nTotal number of unique countries: {unique_countries_count}")
print(f"Total number of columns: {len(sales_shipping_data.columns)}")
print(f"Total number of rows: {len(sales_shipping_data)}")

sales_shipping_data.info()

# ======== No need for this since I used df.info() function to print out the details ========
# Calculate statistics for and print the result
# for c in sales_shipping_data.columns:
#     print(f"\n--- Column: '{c}' ---")

#     # Get the count of unique values
#     unique_count = sales_shipping_data[c].nunique()
#     print(f"Unique Values: {unique_count}")

#     # Get the number of missing values
#     missing_count = sales_shipping_data[c].isnull().sum()
#     print(f"Missing Values: {missing_count}")

    
#     if(c in numerical_columns.columns):
#         print(f"Min: ${numerical_columns[c].min():,.2f}")
#         print(f"Max: ${numerical_columns[c].max():,.2f}")
#         print(f"Mean: ${numerical_columns[c].mean():,.2f}")

# sales_shipping_data.head()

Total number of unique countries: 171
Total number of columns: 22
Total number of rows: 500
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Region               500 non-null    object
 1   Country              500 non-null    object
 2   Item Type            500 non-null    object
 3   Sales Channel        500 non-null    object
 4   Order Priority       500 non-null    object
 5   Order Date           500 non-null    object
 6   Order ID             500 non-null    int64
 7   Ship Date            500 non-null    object
 8   Units Sold           500 non-null    int64
 9   Unit Price           500 non-null    float64
 10  Unit Cost            500 non-null    float64
 11  Total Revenue        500 non-null    float64
 12  Total Cost           500 non-null    float64
 13  Total Profit         500 non-null    float64
 14  Shipping Address ID  500 non-null    int64
 15  shipping_address_id  500 non-null    int64
 16  country              500 non-null    object
 17  street               500 non-null    object
 18  city                 500 non-null    object
 19  state/province       500 non-null    object
 20  postal_code          500 non-null    float64
 21  phone_number         500 non-null    object
dtypes: float64(6), int64(4), object(12)
memory usage: 86.1+ KB

#### Step 6: Spot the Grime - Identify at least three dirty data cases

#### Step 7: Cleaning Rules - Execute fixes inside clean(); show “before/after” counts

In [426]:
# Data Cleaning and Normalization

# 1. Remove leading/trailing whitespace from string columns
for col in sales_shipping_data.select_dtypes(include='object').columns:
  sales_shipping_data[col] = sales_shipping_data[col].str.strip()


# 2. Remove the columns 'country' and 'shipping_address_id' since they are dupplicated and they come from both datasets
sales_shipping_data.drop(columns=['country'], inplace=True)
sales_shipping_data.drop(columns=['shipping_address_id'], inplace=True)
    
# 3. Standardize column names (lowercase, replace spaces with underscores)
sales_shipping_data.columns = [col.strip().lower().replace(' ', '_') for col in sales_shipping_data.columns]

# 4. Columns should be numeric whenever possible - replacing online/offline with 1/0
for i in range(len(sales_shipping_data)):
  if sales_shipping_data.loc[i, "sales_channel"].lower() == "online":
    sales_shipping_data.loc[i, "sales_channel"] = 1
  elif sales_shipping_data.loc[i, "sales_channel"].lower() == "offline":
    sales_shipping_data.loc[i, "sales_channel"] = 0
  else:
    sales_shipping_data.loc[i, "sales_channel"] = np.nan

# Check result"
sales_shipping_data.head(len(sales_shipping_data))

,region,country,item_type,sales_channel,order_priority,order_date,order_id,ship_date,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit,shipping_address_id,street,city,state/province,postal_code,phone_number
0,Middle East and North Africa,Libya,Cosmetics,0,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02,85831,1069 Main St,Sydney,ENG,33769.0,Phone Number
1,North America,Canada,Vegetables,1,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34,72252,8872 Main St,Toronto,NY,98001.0,Phone Number
2,Middle East and North Africa,Libya,Baby Food,0,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62,92369,2924 Main St,Tokyo,BE,97404.0,Phone Number
3,Asia,Japan,Cereal,0,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98,56245,1311 Main St,New York,BE,30156.0,Phone Number
4,Sub-Saharan Africa,Chad,Fruits,0,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45,86737,329 Main St,London,ON,95836.0,Phone Number
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Middle East and North Africa,Algeria,Meat,0,M,9/2/2011,183022201,10/15/2011,9191,421.89,364.69,3877590.99,3351865.79,525725.20,94611,440 Main St,Tokyo,ON,23406.0,Phone Number
496,Europe,Italy,Personal Care,1,L,3/21/2011,127589738,4/2/2011,5494,81.73,56.67,449024.62,311344.98,137679.64,22835,7522 Main St,Tokyo,ON,29781.0,Phone Number
497,Europe,Russia,Fruits,0,L,1/8/2011,221530139,1/26/2011,4546,9.33,6.92,42414.18,31458.32,10955.86,87376,4233 Main St,Toronto,ENG,67417.0,Phone Number
498,Central America and the Caribbean,Antigua and Barbuda,Office Supplies,0,M,2/22/2015,363329732,2/22/2015,6197,651.21,524.96,4035548.37,3253177.12,782371.25,25966,759 Main St,London,NY,28325.0,Phone Number
499,Middle East and North Africa,Jordan,Fruits,1,C,5/15/2017,521787345,6/25/2017,7325,9.33,6.92,68342.25,50689.00,17653.25,51939,9852 Main St,New York,BE,78684.0,Phone Number

In [427]:
# Generate 9 random 5-digit numbers
coupon_codes = np.random.choice(range(10000, 99999), size=9, replace=False)

# Make discount choices, including None for missing values
discount_choices = [5, 10, 15, 20, 25, 30, None]

# Generate exactly 9 discount values
discount_options = np.random.choice(discount_choices, size=9, replace=True)

# Build DataFrame
coupon_df = pd.DataFrame({
    "COUPON CODE": list(coupon_codes),
    "DISCOUNT_PERCENTAGE": list(discount_options)
})

# Save to CSV
coupon_df.to_csv("./data/coupon_codes.csv", index=False)

# Add the new 'Coupon Code' column to the DataFrame
sales_shipping_data['COUPON CODE'] = np.random.choice(coupon_codes, size=len(sales_shipping_data))
print("New 'Coupon Code' column added with random 5-digit numbers!")

# Function to apply discount by going over the data row by row
# When running it this way, it takes 3 seconds to go over 500 rows
# def apply_discount(row):
#     # Load coupon dataset each time (or move outside for efficiency)
#     coupon_csv_path = "./data/coupon_codes.csv"
#     coupon_df = pd.read_csv(coupon_csv_path)

#     condition = coupon_df["COUPON CODE"] == row["COUPON CODE"]

#     selected_row_df = coupon_df.loc[condition]

#     if np.isnan(selected_row_df["DISCOUNT_PERCENTAGE"]).iloc[0]:
#         row["total_revenue_after_disc"] = row["total_revenue"]
#         row["total_profit_after_disc"] = row["total_profit"]
#     else:
#         row["total_revenue_after_disc"] = round(row["total_revenue"] * (1 - selected_row_df["DISCOUNT_PERCENTAGE"].iloc[0] / 100), 2)
#         row["total_profit_after_disc"] = round(row["total_profit"] * (1 - selected_row_df["DISCOUNT_PERCENTAGE"].iloc[0] / 100), 2)

#     return row

# Apply the function row by row
# sales_shipping_data = sales_shipping_data.apply(apply_discount, axis=1)

# When merging the datasets together to appy discounts, it takes maximum 0.3 second to go over 500 rows and apply discounts
def apply_discounts(sales_df):
    coupon_csv_path = "./data/coupon_codes.csv"
    coupons_df = pd.read_csv(coupon_csv_path)

    # Normalize column names for consistency
    coupons_df = coupons_df.rename(columns={"COUPON CODE": "coupon_code"})
    coupons_df = coupons_df.rename(columns={"DISCOUNT_PERCENTAGE": "discount_percentage"})
    
    sales_df = sales_df.rename(columns={"COUPON CODE": "coupon_code"})
    
    # Merge on coupon_code (left join to keep all sales)
    merged = sales_df.merge(coupons_df, on="coupon_code", how="left")

    # Replace missing discounts with 0
    merged["discount_percentage"] = merged["discount_percentage"].fillna(0)

    # Compute discounted values
    merged["total_revenue_after_disc"] = round(
        merged["total_revenue"] * (1 - merged["discount_percentage"] / 100), 2
    )
    merged["total_profit_after_disc"] = round(
        merged["total_profit"] * (1 - merged["discount_percentage"] / 100), 2
    )

    # Removing DISOUNT_PERCENTAGE column
    merged = merged.drop("discount_percentage", axis=1)

    return merged

sales_shipping_data = apply_discounts(sales_shipping_data)

sales_shipping_data.head(len(sales_records_path))

New 'Coupon Code' column added with random 5-digit numbers!

,region,country,item_type,sales_channel,order_priority,order_date,order_id,ship_date,units_sold,unit_price,...,total_profit,shipping_address_id,street,city,state/province,postal_code,phone_number,coupon_code,total_revenue_after_disc,total_profit_after_disc
0,Middle East and North Africa,Libya,Cosmetics,0,M,10/18/2014,686800706,10/31/2014,8446,437.20,...,1468506.02,85831,1069 Main St,Sydney,ENG,33769.0,Phone Number,98507,2584813.84,1027954.21
1,North America,Canada,Vegetables,1,M,11/7/2011,185941302,12/8/2011,3018,154.06,...,190526.34,72252,8872 Main St,Toronto,NY,98001.0,Phone Number,49164,418457.77,171473.71
2,Middle East and North Africa,Libya,Baby Food,0,C,10/31/2016,246222341,12/9/2016,1517,255.28,...,145419.62,92369,2924 Main St,Tokyo,BE,97404.0,Phone Number,98507,271081.83,101793.73
3,Asia,Japan,Cereal,0,C,4/10/2010,161442649,5/12/2010,3322,205.70,...,294295.98,56245,1311 Main St,New York,BE,30156.0,Phone Number,49164,615001.86,264866.38
4,Sub-Saharan Africa,Chad,Fruits,0,H,8/16/2011,645713555,8/31/2011,9845,9.33,...,23726.45,86737,329 Main St,London,ON,95836.0,Phone Number,82743,68890.39,17794.84
5,Europe,Armenia,Cereal,1,H,11/24/2014,683458888,12/28/2014,9528,205.70,...,844085.52,31708,4384 Main St,Berlin,NY,60481.0,Phone Number,95341,1567927.68,675268.42
6,Sub-Saharan Africa,Eritrea,Cereal,1,H,3/4/2015,679414975,4/17/2015,2844,205.70,...,251949.96,16640,3285 Main St,Berlin,ON,23435.0,Phone Number,98507,409507.56,176364.97
7,Europe,Montenegro,Clothes,0,M,5/17/2012,208630645,6/28/2012,7299,109.28,...,536038.56,36315,601 Main St,Sydney,BE,79650.0,Phone Number,72705,558344.30,375226.99
8,Central America and the Caribbean,Jamaica,Vegetables,1,H,1/29/2015,266467225,3/7/2015,2428,154.06,...,153279.64,41310,148 Main St,Sydney,BE,56336.0,Phone Number,95341,299246.14,122623.71
9,Australia and Oceania,Fiji,Vegetables,0,H,12/24/2013,118598544,1/19/2014,4800,154.06,...,303024.00,96451,3666 Main St,New York,NY,46135.0,Phone Number,95341,591590.40,242419.20
10,Sub-Saharan Africa,Togo,Clothes,1,M,12/29/2015,451010930,1/19/2016,3012,109.28,...,221201.28,74890,3155 Main St,Tokyo,ON,83631.0,Phone Number,49164,296236.22,199081.15
11,Europe,Montenegro,Snacks,0,M,2/27/2010,220003211,3/18/2010,2694,152.58,...,148547.16,26661,8980 Main St,Toronto,ON,47909.0,Phone Number,62120,328840.42,118837.73
12,Europe,Greece,Household,1,C,11/17/2016,702186715,12/22/2016,1508,668.27,...,249920.84,19100,486 Main St,Tokyo,NY,79487.0,Phone Number,72705,705425.81,174944.59
13,Sub-Saharan Africa,Sudan,Cosmetics,1,C,12/20/2015,544485270,1/5/2016,4146,437.20,...,720865.02,90864,1069 Main St,Tokyo,ON,31468.0,Phone Number,98507,1268841.84,504605.51
14,Asia,Maldives,Fruits,0,L,1/8/2011,714135205,2/6/2011,7332,9.33,...,17670.12,18205,9297 Main St,Tokyo,TYO,57655.0,Phone Number,72705,47885.29,12369.08
15,Europe,Montenegro,Clothes,0,H,6/28/2010,448685348,7/22/2010,4820,109.28,...,353980.80,32256,5920 Main St,New York,BE,44341.0,Phone Number,98507,368710.72,247786.56
16,Europe,Estonia,Office Supplies,1,H,4/25/2016,405997025,5/12/2016,2397,651.21,...,302621.25,23303,3152 Main St,New York,NSW,74182.0,Phone Number,82743,1170712.78,226965.94
17,North America,Greenland,Beverages,1,M,7/27/2012,414244067,8/7/2012,2880,47.45,...,45100.80,83142,7497 Main St,Toronto,ENG,61786.0,Phone Number,82743,102492.00,33825.60
18,Sub-Saharan Africa,Cape Verde,Clothes,1,C,9/8/2014,821912801,10/3/2014,1117,109.28,...,82032.48,82867,2402 Main St,Tokyo,ON,78304.0,Phone Number,98507,85446.03,57422.74
19,Sub-Saharan Africa,Senegal,Household,0,L,8/27/2012,247802054,9/8/2012,8989,668.27,...,1489746.97,44974,2383 Main St,New York,ON,56514.0,Phone Number,49164,5406371.13,1340772.27
20,Australia and Oceania,Federated States of Micronesia,Snacks,1,C,9/3/2012,531023156,10/15/2012,407,152.58,...,22441.98,34853,9899 Main St,Toronto,ENG,43979.0,Phone Number,56265,43470.04,15709.39
21,Europe,Bulgaria,Clothes,1,L,8/27/2010,880999934,9/16/2010,6313,109.28,...,463626.72,18721,4466 Main St,Berlin,ON,90981.0,Phone Number,56265,482919.25,324538.70
22,Middle East and North Africa,Algeria,Personal Care,1,H,2/20/2011,127468717,3/9/2011,9681,81.73,...,242605.86,54216,222 Main St,Toronto,ENG,65107.0,Phone Number,86224,672543.91,206214.98
23,Asia,Mongolia,Clothes,1,L,12/12/2015,770478332,1/24/2016,515,109.28,...,37821.60,83452,6899 Main St,Tokyo,NY,11160.0,Phone Number,72705,39395.44,26475.12
24,Central America and the Caribbean,Grenada,Cereal,1,H,10/28/2012,430390107,11/13/2012,852,205.70,...,75478.68,33064,9572 Main St,London,TYO,97897.0,Phone Number,95341,140205.12,60382.94
25,Central America and the Caribbean,Grenada,Beverages,1,M,1/30/2017,397877871,3/20/2017,9759,47.45,...,152825.94,61142,3827 Main St,Tokyo,TYO,82577.0,Phone Number,98507,324145.18,106978.16
26,Sub-Saharan Africa,Senegal,Beverages,0,M,10/22/2014,683927953,11/4/2014,8334,47.45,...,130510.44,48328,8550 Main St,London,BE,94303.0,Phone Number,86224,336131.06,110933.87
27,North America,Greenland,Fruits,0,M,1/31/2012,469839179,2/22/2012,4709,9.33,...,11348.69,90079,9239 Main St,Toronto,NSW,20846.0,Phone Number,86224,37344.72,9646.39
28,Sub-Saharan Africa,Chad,Meat,0,H,1/20/2016,357222878,3/9/2016,9043,421.89,...,517259.60,32575,5058 Main St,Berlin,ON,29924.0,Phone Number,95341,3052121.02,413807.68
29,Sub-Saharan Africa,Mauritius,Personal Care,1,C,1/1/2016,118002879,1/7/2016,8529,81.73,...,213736.74,98435,624 Main St,Berlin,NSW,23882.0,Phone Number,95341,557660.14,170989.39
30,Middle East and North Africa,Morocco,Beverages,0,C,6/1/2017,944415509,6/23/2017,2391,47.45,...,37443.06,13556,9179 Main St,New York,NY,90274.0,Phone Number,86224,96435.01,31826.60
31,Central America and the Caribbean,Honduras,Office Supplies,1,H,6/30/2015,499009597,7/9/2015,6884,651.21,...,869105.00,59464,8499 Main St,Berlin,TYO,96555.0,Phone Number,82743,3362197.23,651828.75
32,Sub-Saharan Africa,Benin,Fruits,1,L,1/28/2014,564646470,3/16/2014,293,9.33,...,706.13,10220,248 Main St,Sydney,NY,11095.0,Phone Number,95341,2186.95,564.90
33,Europe,Greece,Baby Food,0,M,4/8/2014,294499957,4/8/2014,7937,255.28,...,760840.82,54200,8101 Main St,Toronto,NY,50983.0,Phone Number,95341,1620925.89,608672.66
34,Central America and the Caribbean,Jamaica,Beverages,0,L,9/4/2010,262056386,10/24/2010,7163,47.45,...,112172.58,14327,537 Main St,New York,ON,24123.0,Phone Number,49164,305895.91,100955.32
35,Sub-Saharan Africa,Equatorial Guinea,Office Supplies,1,M,5/2/2010,211114585,5/14/2010,2352,651.21,...,296940.00,94362,3849 Main St,Berlin,NY,76615.0,Phone Number,62120,1225316.74,237552.00
36,Sub-Saharan Africa,Swaziland,Office Supplies,0,H,10/3/2013,405785882,10/22/2013,9915,651.21,...,1251768.75,38399,8286 Main St,Toronto,TYO,55278.0,Phone Number,56265,4519723.00,876238.12
37,Central America and the Caribbean,Trinidad and Tobago,Vegetables,0,M,3/6/2011,280494105,4/14/2011,3294,154.06,...,207950.22,58459,4553 Main St,Tokyo,NSW,61999.0,Phone Number,62120,405978.91,166360.18
38,Europe,Sweden,Baby Food,1,L,8/7/2016,689975583,8/12/2016,7963,255.28,...,763333.18,70584,5436 Main St,Berlin,TYO,41153.0,Phone Number,82743,1524595.98,572499.88
39,Europe,Belarus,Office Supplies,1,L,1/11/2011,759279143,2/18/2011,6426,651.21,...,811282.50,47396,4651 Main St,London,ON,28344.0,Phone Number,72705,2929272.82,567897.75
40,Sub-Saharan Africa,Guinea-Bissau,Office Supplies,0,C,5/21/2014,133766114,6/12/2014,3221,651.21,...,406651.25,27792,2923 Main St,Toronto,TYO,47656.0,Phone Number,49164,1887792.67,365986.12
41,Asia,Mongolia,Beverages,1,M,8/3/2013,329110324,9/2/2013,9913,47.45,...,155237.58,67806,5828 Main St,New York,ENG,80515.0,Phone Number,95341,376297.48,124190.06
42,Middle East and North Africa,Turkey,Meat,1,L,10/5/2011,681298100,11/20/2011,103,421.89,...,5891.60,25978,8777 Main St,Tokyo,NSW,11212.0,Phone Number,89724,34763.74,4713.28
43,Sub-Saharan Africa,Central African Republic,Snacks,0,L,11/15/2016,596628272,12/30/2016,4419,152.58,...,243663.66,55076,8491 Main St,Sydney,ENG,19001.0,Phone Number,86224,573113.37,207114.11
44,Sub-Saharan Africa,Equatorial Guinea,Office Supplies,0,L,4/3/2015,901712167,4/17/2015,5523,651.21,...,697278.75,92550,2082 Main St,Tokyo,ENG,88784.0,Phone Number,89724,2877306.26,557823.00
45,Asia,Laos,Beverages,1,M,3/22/2013,693473613,4/21/2013,3107,47.45,...,48655.62,61264,7096 Main St,Berlin,BE,91144.0,Phone Number,98507,103199.00,34058.93
46,Europe,Armenia,Meat,1,C,8/2/2010,489148938,9/1/2010,8896,421.89,...,508851.20,29627,9763 Main St,London,ON,46427.0,Phone Number,49164,3377820.10,457966.08
47,Europe,Greece,Household,1,L,1/5/2012,876286971,2/15/2012,1643,668.27,...,272294.39,60308,2411 Main St,Tokyo,NY,41368.0,Phone Number,89724,878374.09,217835.51
48,Middle East and North Africa,Israel,Personal Care,0,H,8/26/2015,262749040,8/30/2015,2135,81.73,...,53503.10,86164,7325 Main St,Sydney,ENG,80819.0,Phone Number,89724,139594.84,42802.48
49,Asia,Bhutan,Meat,1,H,12/9/2016,726708972,1/26/2017,8189,421.89,...,468410.80,68321,9813 Main St,New York,TYO,71160.0,Phone Number,95341,2763885.77,374728.64
50,Australia and Oceania,Vanuatu,Vegetables,1,L,5/17/2012,366653096,5/31/2012,9654,154.06,...,609457.02,17692,704 Main St,Toronto,NY,35854.0,Phone Number,86224,1264200.95,518038.47
51,Sub-Saharan Africa,Burundi,Vegetables,1,M,11/17/2010,951380240,12/20/2010,3410,154.06,...,215273.30,89690,8275 Main St,London,TYO,20715.0,Phone Number,62120,420275.68,172218.64

#### 9. Feature Engineering - For example: Add days_since_purchase

In [428]:
def add_days_since_purchase(df):
    date_col="order_date"
    # Ensure the column is datetime
    df[date_col] = pd.to_datetime(df[date_col], errors="coerce")

    # Compute days since purchase
    today = pd.Timestamp.today().normalize()  # removes time portion
    df["days_since_purchase"] = (today - df[date_col]).dt.days

    return df

sales_shipping_data = add_days_since_purchase(sales_shipping_data)

sales_shipping_data.head(len(sales_records_path))

,region,country,item_type,sales_channel,order_priority,order_date,order_id,ship_date,units_sold,unit_price,...,shipping_address_id,street,city,state/province,postal_code,phone_number,coupon_code,total_revenue_after_disc,total_profit_after_disc,days_since_purchase
0,Middle East and North Africa,Libya,Cosmetics,0,M,2014-10-18,686800706,10/31/2014,8446,437.20,...,85831,1069 Main St,Sydney,ENG,33769.0,Phone Number,98507,2584813.84,1027954.21,3997
1,North America,Canada,Vegetables,1,M,2011-11-07,185941302,12/8/2011,3018,154.06,...,72252,8872 Main St,Toronto,NY,98001.0,Phone Number,49164,418457.77,171473.71,5073
2,Middle East and North Africa,Libya,Baby Food,0,C,2016-10-31,246222341,12/9/2016,1517,255.28,...,92369,2924 Main St,Tokyo,BE,97404.0,Phone Number,98507,271081.83,101793.73,3253
3,Asia,Japan,Cereal,0,C,2010-04-10,161442649,5/12/2010,3322,205.70,...,56245,1311 Main St,New York,BE,30156.0,Phone Number,49164,615001.86,264866.38,5649
4,Sub-Saharan Africa,Chad,Fruits,0,H,2011-08-16,645713555,8/31/2011,9845,9.33,...,86737,329 Main St,London,ON,95836.0,Phone Number,82743,68890.39,17794.84,5156
5,Europe,Armenia,Cereal,1,H,2014-11-24,683458888,12/28/2014,9528,205.70,...,31708,4384 Main St,Berlin,NY,60481.0,Phone Number,95341,1567927.68,675268.42,3960
6,Sub-Saharan Africa,Eritrea,Cereal,1,H,2015-03-04,679414975,4/17/2015,2844,205.70,...,16640,3285 Main St,Berlin,ON,23435.0,Phone Number,98507,409507.56,176364.97,3860
7,Europe,Montenegro,Clothes,0,M,2012-05-17,208630645,6/28/2012,7299,109.28,...,36315,601 Main St,Sydney,BE,79650.0,Phone Number,72705,558344.30,375226.99,4881
8,Central America and the Caribbean,Jamaica,Vegetables,1,H,2015-01-29,266467225,3/7/2015,2428,154.06,...,41310,148 Main St,Sydney,BE,56336.0,Phone Number,95341,299246.14,122623.71,3894
9,Australia and Oceania,Fiji,Vegetables,0,H,2013-12-24,118598544,1/19/2014,4800,154.06,...,96451,3666 Main St,New York,NY,46135.0,Phone Number,95341,591590.40,242419.20,4295
10,Sub-Saharan Africa,Togo,Clothes,1,M,2015-12-29,451010930,1/19/2016,3012,109.28,...,74890,3155 Main St,Tokyo,ON,83631.0,Phone Number,49164,296236.22,199081.15,3560
11,Europe,Montenegro,Snacks,0,M,2010-02-27,220003211,3/18/2010,2694,152.58,...,26661,8980 Main St,Toronto,ON,47909.0,Phone Number,62120,328840.42,118837.73,5691
12,Europe,Greece,Household,1,C,2016-11-17,702186715,12/22/2016,1508,668.27,...,19100,486 Main St,Tokyo,NY,79487.0,Phone Number,72705,705425.81,174944.59,3236
13,Sub-Saharan Africa,Sudan,Cosmetics,1,C,2015-12-20,544485270,1/5/2016,4146,437.20,...,90864,1069 Main St,Tokyo,ON,31468.0,Phone Number,98507,1268841.84,504605.51,3569
14,Asia,Maldives,Fruits,0,L,2011-01-08,714135205,2/6/2011,7332,9.33,...,18205,9297 Main St,Tokyo,TYO,57655.0,Phone Number,72705,47885.29,12369.08,5376
15,Europe,Montenegro,Clothes,0,H,2010-06-28,448685348,7/22/2010,4820,109.28,...,32256,5920 Main St,New York,BE,44341.0,Phone Number,98507,368710.72,247786.56,5570
16,Europe,Estonia,Office Supplies,1,H,2016-04-25,405997025,5/12/2016,2397,651.21,...,23303,3152 Main St,New York,NSW,74182.0,Phone Number,82743,1170712.78,226965.94,3442
17,North America,Greenland,Beverages,1,M,2012-07-27,414244067,8/7/2012,2880,47.45,...,83142,7497 Main St,Toronto,ENG,61786.0,Phone Number,82743,102492.00,33825.60,4810
18,Sub-Saharan Africa,Cape Verde,Clothes,1,C,2014-09-08,821912801,10/3/2014,1117,109.28,...,82867,2402 Main St,Tokyo,ON,78304.0,Phone Number,98507,85446.03,57422.74,4037
19,Sub-Saharan Africa,Senegal,Household,0,L,2012-08-27,247802054,9/8/2012,8989,668.27,...,44974,2383 Main St,New York,ON,56514.0,Phone Number,49164,5406371.13,1340772.27,4779
20,Australia and Oceania,Federated States of Micronesia,Snacks,1,C,2012-09-03,531023156,10/15/2012,407,152.58,...,34853,9899 Main St,Toronto,ENG,43979.0,Phone Number,56265,43470.04,15709.39,4772
21,Europe,Bulgaria,Clothes,1,L,2010-08-27,880999934,9/16/2010,6313,109.28,...,18721,4466 Main St,Berlin,ON,90981.0,Phone Number,56265,482919.25,324538.70,5510
22,Middle East and North Africa,Algeria,Personal Care,1,H,2011-02-20,127468717,3/9/2011,9681,81.73,...,54216,222 Main St,Toronto,ENG,65107.0,Phone Number,86224,672543.91,206214.98,5333
23,Asia,Mongolia,Clothes,1,L,2015-12-12,770478332,1/24/2016,515,109.28,...,83452,6899 Main St,Tokyo,NY,11160.0,Phone Number,72705,39395.44,26475.12,3577
24,Central America and the Caribbean,Grenada,Cereal,1,H,2012-10-28,430390107,11/13/2012,852,205.70,...,33064,9572 Main St,London,TYO,97897.0,Phone Number,95341,140205.12,60382.94,4717
25,Central America and the Caribbean,Grenada,Beverages,1,M,2017-01-30,397877871,3/20/2017,9759,47.45,...,61142,3827 Main St,Tokyo,TYO,82577.0,Phone Number,98507,324145.18,106978.16,3162
26,Sub-Saharan Africa,Senegal,Beverages,0,M,2014-10-22,683927953,11/4/2014,8334,47.45,...,48328,8550 Main St,London,BE,94303.0,Phone Number,86224,336131.06,110933.87,3993
27,North America,Greenland,Fruits,0,M,2012-01-31,469839179,2/22/2012,4709,9.33,...,90079,9239 Main St,Toronto,NSW,20846.0,Phone Number,86224,37344.72,9646.39,4988
28,Sub-Saharan Africa,Chad,Meat,0,H,2016-01-20,357222878,3/9/2016,9043,421.89,...,32575,5058 Main St,Berlin,ON,29924.0,Phone Number,95341,3052121.02,413807.68,3538
29,Sub-Saharan Africa,Mauritius,Personal Care,1,C,2016-01-01,118002879,1/7/2016,8529,81.73,...,98435,624 Main St,Berlin,NSW,23882.0,Phone Number,95341,557660.14,170989.39,3557
30,Middle East and North Africa,Morocco,Beverages,0,C,2017-06-01,944415509,6/23/2017,2391,47.45,...,13556,9179 Main St,New York,NY,90274.0,Phone Number,86224,96435.01,31826.60,3040
31,Central America and the Caribbean,Honduras,Office Supplies,1,H,2015-06-30,499009597,7/9/2015,6884,651.21,...,59464,8499 Main St,Berlin,TYO,96555.0,Phone Number,82743,3362197.23,651828.75,3742
32,Sub-Saharan Africa,Benin,Fruits,1,L,2014-01-28,564646470,3/16/2014,293,9.33,...,10220,248 Main St,Sydney,NY,11095.0,Phone Number,95341,2186.95,564.90,4260
33,Europe,Greece,Baby Food,0,M,2014-04-08,294499957,4/8/2014,7937,255.28,...,54200,8101 Main St,Toronto,NY,50983.0,Phone Number,95341,1620925.89,608672.66,4190
34,Central America and the Caribbean,Jamaica,Beverages,0,L,2010-09-04,262056386,10/24/2010,7163,47.45,...,14327,537 Main St,New York,ON,24123.0,Phone Number,49164,305895.91,100955.32,5502
35,Sub-Saharan Africa,Equatorial Guinea,Office Supplies,1,M,2010-05-02,211114585,5/14/2010,2352,651.21,...,94362,3849 Main St,Berlin,NY,76615.0,Phone Number,62120,1225316.74,237552.00,5627
36,Sub-Saharan Africa,Swaziland,Office Supplies,0,H,2013-10-03,405785882,10/22/2013,9915,651.21,...,38399,8286 Main St,Toronto,TYO,55278.0,Phone Number,56265,4519723.00,876238.12,4377
37,Central America and the Caribbean,Trinidad and Tobago,Vegetables,0,M,2011-03-06,280494105,4/14/2011,3294,154.06,...,58459,4553 Main St,Tokyo,NSW,61999.0,Phone Number,62120,405978.91,166360.18,5319
38,Europe,Sweden,Baby Food,1,L,2016-08-07,689975583,8/12/2016,7963,255.28,...,70584,5436 Main St,Berlin,TYO,41153.0,Phone Number,82743,1524595.98,572499.88,3338
39,Europe,Belarus,Office Supplies,1,L,2011-01-11,759279143,2/18/2011,6426,651.21,...,47396,4651 Main St,London,ON,28344.0,Phone Number,72705,2929272.82,567897.75,5373
40,Sub-Saharan Africa,Guinea-Bissau,Office Supplies,0,C,2014-05-21,133766114,6/12/2014,3221,651.21,...,27792,2923 Main St,Toronto,TYO,47656.0,Phone Number,49164,1887792.67,365986.12,4147
41,Asia,Mongolia,Beverages,1,M,2013-08-03,329110324,9/2/2013,9913,47.45,...,67806,5828 Main St,New York,ENG,80515.0,Phone Number,95341,376297.48,124190.06,4438
42,Middle East and North Africa,Turkey,Meat,1,L,2011-10-05,681298100,11/20/2011,103,421.89,...,25978,8777 Main St,Tokyo,NSW,11212.0,Phone Number,89724,34763.74,4713.28,5106
43,Sub-Saharan Africa,Central African Republic,Snacks,0,L,2016-11-15,596628272,12/30/2016,4419,152.58,...,55076,8491 Main St,Sydney,ENG,19001.0,Phone Number,86224,573113.37,207114.11,3238
44,Sub-Saharan Africa,Equatorial Guinea,Office Supplies,0,L,2015-04-03,901712167,4/17/2015,5523,651.21,...,92550,2082 Main St,Tokyo,ENG,88784.0,Phone Number,89724,2877306.26,557823.00,3830
45,Asia,Laos,Beverages,1,M,2013-03-22,693473613,4/21/2013,3107,47.45,...,61264,7096 Main St,Berlin,BE,91144.0,Phone Number,98507,103199.00,34058.93,4572
46,Europe,Armenia,Meat,1,C,2010-08-02,489148938,9/1/2010,8896,421.89,...,29627,9763 Main St,London,ON,46427.0,Phone Number,49164,3377820.10,457966.08,5535
47,Europe,Greece,Household,1,L,2012-01-05,876286971,2/15/2012,1643,668.27,...,60308,2411 Main St,Tokyo,NY,41368.0,Phone Number,89724,878374.09,217835.51,5014
48,Middle East and North Africa,Israel,Personal Care,0,H,2015-08-26,262749040,8/30/2015,2135,81.73,...,86164,7325 Main St,Sydney,ENG,80819.0,Phone Number,89724,139594.84,42802.48,3685
49,Asia,Bhutan,Meat,1,H,2016-12-09,726708972,1/26/2017,8189,421.89,...,68321,9813 Main St,New York,TYO,71160.0,Phone Number,95341,2763885.77,374728.64,3214
50,Australia and Oceania,Vanuatu,Vegetables,1,L,2012-05-17,366653096,5/31/2012,9654,154.06,...,17692,704 Main St,Toronto,NY,35854.0,Phone Number,86224,1264200.95,518038.47,4881
51,Sub-Saharan Africa,Burundi,Vegetables,1,M,2010-11-17,951380240,12/20/2010,3410,154.06,...,89690,8275 Main St,London,TYO,20715.0,Phone Number,62120,420275.68,172218.64,5428

#### 10. Mini-Aggregation - For example: Revenue per shipping_city (dict or pandas.groupby)

In [429]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(df):
    # Performed 1 aggregation grouped on column: 'city'
    df = df.groupby(['city']).agg(total_revenue_sum=('total_revenue', 'sum')).reset_index()
    return df

# Loaded variable 'df' from kernel state
df = sales_shipping_data.head(len(sales_records_path))

df_clean = clean_data(df.copy())
df_clean.head()

       city  total_revenue_sum
0    Berlin        15941828.83
1    London         9125712.05
2  New York        13896148.76
3    Sydney         5715761.86
4     Tokyo         9492139.30

#### 11. Serialization Checkpoint - Save cleaned data to JSON

In [430]:
# Convert to JSON (records format is usually the most useful)
json_str = sales_shipping_data.to_json(orient="records", indent=2)

print(json_str)

[
  {
    "region":"Middle East and North Africa",
    "country":"Libya",
    "item_type":"Cosmetics",
    "sales_channel":0,
    "order_priority":"M",
    "order_date":1413590400000,
    "order_id":686800706,
    "ship_date":"10\/31\/2014",
    "units_sold":8446,
    "unit_price":437.2,
    "unit_cost":263.33,
    "total_revenue":3692591.2000000002,
    "total_cost":2224085.1800000002,
    "total_profit":1468506.02,
    "shipping_address_id":85831,
    "street":"1069 Main St",
    "city":"Sydney",
    "state\/province":"ENG",
    "postal_code":33769.0,
    "phone_number":"Phone Number",
    "coupon_code":98507,
    "total_revenue_after_disc":2584813.8399999999,
    "total_profit_after_disc":1027954.21,
    "days_since_purchase":3997
  },
  {
    "region":"North America",
    "country":"Canada",
    "item_type":"Vegetables",
    "sales_channel":1,
    "order_priority":"M",
    "order_date":1320624000000,
    "order_id":185941302,
    "ship_date":"12\/8\/2011",
    "units_sold":3018,
    "unit_price":154.06,
    "unit_cost":90.93,
    "total_revenue":464953.08,
    "total_cost":274426.74,
    "total_profit":190526.34,
    "shipping_address_id":72252,
    "street":"8872 Main St",
    "city":"Toronto",
    "state\/province":"NY",
    "postal_code":98001.0,
    "phone_number":"Phone Number",
    "coupon_code":49164,
    "total_revenue_after_disc":418457.77,
    "total_profit_after_disc":171473.71,
    "days_since_purchase":5073
  },
  {
    "region":"Middle East and North Africa",
    "country":"Libya",
    "item_type":"Baby Food",
    "sales_channel":0,
    "order_priority":"C",
    "order_date":1477872000000,
    "order_id":246222341,
    "ship_date":"12\/9\/2016",
    "units_sold":1517,
    "unit_price":255.28,
    "unit_cost":159.42,
    "total_revenue":387259.76,
    "total_cost":241840.14,
    "total_profit":145419.62,
    "shipping_address_id":92369,
    "street":"2924 Main St",
    "city":"Tokyo",
    "state\/province":"BE",
    "postal_code":97404.0,
    "phone_number":"Phone Number",
    "coupon_code":98507,
    "total_revenue_after_disc":271081.83,
    "total_profit_after_disc":101793.73,
    "days_since_purchase":3253
  },
  {
    "region":"Asia",
    "country":"Japan",
    "item_type":"Cereal",
    "sales_channel":0,
    "order_priority":"C",
    "order_date":1270857600000,
    "order_id":161442649,
    "ship_date":"5\/12\/2010",
    "units_sold":3322,
    "unit_price":205.7,
    "unit_cost":117.11,
    "total_revenue":683335.4,
    "total_cost":389039.42,
    "total_profit":294295.98,
    "shipping_address_id":56245,
    "street":"1311 Main St",
    "city":"New York",
    "state\/province":"BE",
    "postal_code":30156.0,
    "phone_number":"Phone Number",
    "coupon_code":49164,
    "total_revenue_after_disc":615001.86,
    "total_profit_after_disc":264866.38,
    "days_since_purchase":5649
  },
  {
    "region":"Sub-Saharan Africa",
    "country":"Chad",
    "item_type":"Fruits",
    "sales_channel":0,
    "order_priority":"H",
    "order_date":1313452800000,
    "order_id":645713555,
    "ship_date":"8\/31\/2011",
    "units_sold":9845,
    "unit_price":9.33,
    "unit_cost":6.92,
    "total_revenue":91853.85,
    "total_cost":68127.4,
    "total_profit":23726.45,
    "shipping_address_id":86737,
    "street":"329 Main St",
    "city":"London",
    "state\/province":"ON",
    "postal_code":95836.0,
    "phone_number":"Phone Number",
    "coupon_code":82743,
    "total_revenue_after_disc":68890.39,
    "total_profit_after_disc":17794.84,
    "days_since_purchase":5156
  },
  {
    "region":"Europe",
    "country":"Armenia",
    "item_type":"Cereal",
    "sales_channel":1,
    "order_priority":"H",
    "order_date":1416787200000,
    "order_id":683458888,
    "ship_date":"12\/28\/2014",
    "units_sold":9528,
    "unit_price":205.7,
    "unit_cost":117.11,
    "total_revenue":1959909.6000000001,
    "total_cost":1115824.0800000001,
    "total_profit":844085.52,
    "shipping_address_id":31708,
    "street":"4384 Main St",
    "city":"Berlin",
    "state\/province":"NY",
    "postal_code":60481.0,
    "phone_number":"Phone Number",
    "coupon_code":95341,
    "total_revenue_after_disc":1567927.6799999999,
    "total_profit_after_disc":675268.42,
    "days_since_purchase":3960
  },
  {
    "region":"Sub-Saharan Africa",
    "country":"Eritrea",
    "item_type":"Cereal",
    "sales_channel":1,
    "order_priority":"H",
    "order_date":1425427200000,
    "order_id":679414975,
    "ship_date":"4\/17\/2015",
    "units_sold":2844,
    "unit_price":205.7,
    "unit_cost":117.11,
    "total_revenue":585010.8,
    "total_cost":333060.84,
    "total_profit":251949.96,
    "shipping_address_id":16640,
    "street":"3285 Main St",
    "city":"Berlin",
    "state\/province":"ON",
    "postal_code":23435.0,
    "phone_number":"Phone Number",
    "coupon_code":98507,
    "total_revenue_after_disc":409507.56,
    "total_profit_after_disc":176364.97,
    "days_since_purchase":3860
  },
  {
    "region":"Europe",
    "country":"Montenegro",
    "item_type":"Clothes",
    "sales_channel":0,
    "order_priority":"M",
    "order_date":1337212800000,
    "order_id":208630645,
    "ship_date":"6\/28\/2012",
    "units_sold":7299,
    "unit_price":109.28,
    "unit_cost":35.84,
    "total_revenue":797634.72,
    "total_cost":261596.16,
    "total_profit":536038.5600000001,
    "shipping_address_id":36315,
    "street":"601 Main St",
    "city":"Sydney",
    "state\/province":"BE",
    "postal_code":79650.0,
    "phone_number":"Phone Number",
    "coupon_code":72705,
    "total_revenue_after_disc":558344.3,
    "total_profit_after_disc":375226.99,
    "days_since_purchase":4881
  },
  {
    "region":"Central America and the Caribbean",
    "country":"Jamaica",
    "item_type":"Vegetables",
    "sales_channel":1,
    "order_priority":"H",
    "order_date":1422489600000,
    "order_id":266467225,
    "ship_date":"3\/7\/2015",
    "units_sold":2428,
    "unit_price":154.06,
    "unit_cost":90.93,
    "total_revenue":374057.68,
    "total_cost":220778.04,
    "total_profit":153279.64,
    "shipping_address_id":41310,
    "street":"148 Main St",
    "city":"Sydney",
    "state\/province":"BE",
    "postal_code":56336.0,
    "phone_number":"Phone Number",
    "coupon_code":95341,
    "total_revenue_after_disc":299246.14,
    "total_profit_after_disc":122623.71,
    "days_since_purchase":3894
  },
  {
    "region":"Australia and Oceania",
    "country":"Fiji",
    "item_type":"Vegetables",
    "sales_channel":0,
    "order_priority":"H",
    "order_date":1387843200000,
    "order_id":118598544,
    "ship_date":"1\/19\/2014",
    "units_sold":4800,
    "unit_price":154.06,
    "unit_cost":90.93,
    "total_revenue":739488.0,
    "total_cost":436464.0,
    "total_profit":303024.0,
    "shipping_address_id":96451,
    "street":"3666 Main St",
    "city":"New York",
    "state\/province":"NY",
    "postal_code":46135.0,
    "phone_number":"Phone Number",
    "coupon_code":95341,
    "total_revenue_after_disc":591590.4,
    "total_profit_after_disc":242419.2,
    "days_since_purchase":4295
  },
  {
    "region":"Sub-Saharan Africa",
    "country":"Togo",
    "item_type":"Clothes",
    "sales_channel":1,
    "order_priority":"M",
    "order_date":1451347200000,
    "order_id":451010930,
    "ship_date":"1\/19\/2016",
    "units_sold":3012,
    "unit_price":109.28,
    "unit_cost":35.84,
    "total_revenue":329151.36,
    "total_cost":107950.08,
    "total_profit":221201.28,
    "shipping_address_id":74890,
    "street":"3155 Main St",
    "city":"Tokyo",
    "state\/province":"ON",
    "postal_code":83631.0,
    "phone_number":"Phone Number",
    "coupon_code":49164,
    "total_revenue_after_disc":296236.22,
    "total_profit_after_disc":199081.15,
    "days_since_purchase":3560
  },
  {
    "region":"Europe",
    "country":"Montenegro",
    "item_type":"Snacks",
    "sales_channel":0,
    "order_priority":"M",
    "order_date":1267228800000,
    "order_id":220003211,
    "ship_date":"3\/18\/2010",
    "units_sold":2694,
    "unit_price":152.58,
    "unit_cost":97.44,
    "total_revenue":411050.52,
    "total_cost":262503.36,
    "total_profit":148547.16,
    "shipping_address_id":26661,
    "street":"8980 Main St",
    "city":"Toronto",
    "state\/province":"ON",
    "postal_code":47909.0,
    "phone_number":"Phone Number",
    "coupon_code":62120,
    "total_revenue_after_disc":328840.42,
    "total_profit_after_disc":118837.73,
    "days_since_purchase":5691
  },
  {
    "region":"Europe",
    "country":"Greece",
    "item_type":"Household",
    "sales_channel":1,
    "order_priority":"C",
    "order_date":1479340800000,
    "order_id":702186715,
    "ship_date":"12\/22\/2016",
    "units_sold":1508,
    "unit_price":668.27,
    "unit_cost":502.54,
    "total_revenue":1007751.16,
    "total_cost":757830.3199999999,
    "total_profit":249920.84,
    "shipping_address_id":19100,
    "street":"486 Main St",
    "city":"Tokyo",
    "state\/province":"NY",
    "postal_code":79487.0,
    "phone_number":"Phone Number",
    "coupon_code":72705,
    "total_revenue_after_disc":705425.8100000001,
    "total_profit_after_disc":174944.59,
    "days_since_purchase":3236
  },
  {
    "region":"Sub-Saharan Africa",
    "country":"Sudan",
    "item_type":"Cosmetics",
    "sales_channel":1,
    "order_priority":"C",
    "order_date":1450569600000,
    "order_id":544485270,
    "ship_date":"1\/5\/2016",
    "units_sold":4146,
    "unit_price":437.2,
    "unit_cost":263.33,
    "total_revenue":1812631.2,
    "total_cost":1091766.1799999999,
    "total_profit":720865.02,
    "shipping_address_id":90864,
    "street":"1069 Main St",
    "city":"Tokyo",
    "state\/province":"ON",
    "postal_code":31468.0,
    "phone_number":"Phone Number",
    "coupon_code":98507,
    "total_revenue_after_disc":1268841.8400000001,
    "total_profit_after_disc":504605.51,
    "days_since_purchase":3569
  },
  {
    "region":"Asia",
    "country":"Maldives",
    "item_type":"Fruits",
    "sales_channel":0,
    "order_priority":"L",
    "order_date":1294444800000,
    "order_id":714135205,
    "ship_date":"2\/6\/2011",
    "units_sold":7332,
    "unit_price":9.33,
    "unit_cost":6.92,
    "total_revenue":68407.56,
    "total_cost":50737.44,
    "total_profit":17670.12,
    "shipping_address_id":18205,
    "street":"9297 Main St",
    "city":"Tokyo",
    "state\/province":"TYO",
    "postal_code":57655.0,
    "phone_number":"Phone Number",
    "coupon_code":72705,
    "total_revenue_after_disc":47885.29,
    "total_profit_after_disc":12369.08,
    "days_since_purchase":5376
  },
  {
    "region":"Europe",
    "country":"Montenegro",
    "item_type":"Clothes",
    "sales_channel":0,
    "order_priority":"H",
    "order_date":1277683200000,
    "order_id":448685348,
    "ship_date":"7\/22\/2010",
    "units_sold":4820,
    "unit_price":109.28,
    "unit_cost":35.84,
    "total_revenue":526729.6,
    "total_cost":172748.8,
    "total_profit":353980.8,
    "shipping_address_id":32256,
    "street":"5920 Main St",
    "city":"New York",
    "state\/province":"BE",
    "postal_code":44341.0,
    "phone_number":"Phone Number",
    "coupon_code":98507,
    "total_revenue_after_disc":368710.72,
    "total_profit_after_disc":247786.56,
    "days_since_purchase":5570
  },
  {
    "region":"Europe",
    "country":"Estonia",
    "item_type":"Office Supplies",
    "sales_channel":1,
    "order_priority":"H",
    "order_date":1461542400000,
    "order_id":405997025,
    "ship_date":"5\/12\/2016",
    "units_sold":2397,
    "unit_price":651.21,
    "unit_cost":524.96,
    "total_revenue":1560950.3700000001,
    "total_cost":1258329.1200000001,
    "total_profit":302621.25,
    "shipping_address_id":23303,
    "street":"3152 Main St",
    "city":"New York",
    "state\/province":"NSW",
    "postal_code":74182.0,
    "phone_number":"Phone Number",
    "coupon_code":82743,
    "total_revenue_after_disc":1170712.78,
    "total_profit_after_disc":226965.94,
    "days_since_purchase":3442
  },
  {
    "region":"North America",
    "country":"Greenland",
    "item_type":"Beverages",
    "sales_channel":1,
    "order_priority":"M",
    "order_date":1343347200000,
    "order_id":414244067,
    "ship_date":"8\/7\/2012",
    "units_sold":2880,
    "unit_price":47.45,
    "unit_cost":31.79,
    "total_revenue":136656.0,
    "total_cost":91555.2,
    "total_profit":45100.8,
    "shipping_address_id":83142,
    "street":"7497 Main St",
    "city":"Toronto",
    "state\/province":"ENG",
    "postal_code":61786.0,
    "phone_number":"Phone Number",
    "coupon_code":82743,
    "total_revenue_after_disc":102492.0,
    "total_profit_after_disc":33825.6,
    "days_since_purchase":4810
  },
  {
    "region":"Sub-Saharan Africa",
    "country":"Cape Verde",
    "item_type":"Clothes",
    "sales_channel":1,
    "order_priority":"C",
    "order_date":1410134400000,
    "order_id":821912801,
    "ship_date":"10\/3\/2014",
    "units_sold":1117,
    "unit_price":109.28,
    "unit_cost":35.84,
    "total_revenue":122065.76,
    "total_cost":40033.28,
    "total_profit":82032.48,
    "shipping_address_id":82867,
    "street":"2402 Main St",
    "city":"Tokyo",
    "state\/province":"ON",
    "postal_code":78304.0,
    "phone_number":"Phone Number",
    "coupon_code":98507,
    "total_revenue_after_disc":85446.03,
    "total_profit_after_disc":57422.74,
    "days_since_purchase":4037
  },
  {
    "region":"Sub-Saharan Africa",
    "country":"Senegal",
    "item_type":"Household",
    "sales_channel":0,
    "order_priority":"L",
    "order_date":1346025600000,
    "order_id":247802054,
    "ship_date":"9\/8\/2012",
    "units_sold":8989,
    "unit_price":668.27,
    "unit_cost":502.54,
    "total_revenue":6007079.0300000003,
    "total_cost":4517332.0599999996,
    "total_profit":1489746.97,
    "shipping_address_id":44974,
    "street":"2383 Main St",
    "city":"New York",
    "state\/province":"ON",
    "postal_code":56514.0,
    "phone_number":"Phone Number",
    "coupon_code":49164,
    "total_revenue_after_disc":5406371.1299999999,
    "total_profit_after_disc":1340772.27,
    "days_since_purchase":4779
  },
  {
    "region":"Australia and Oceania",
    "country":"Federated States of Micronesia",
    "item_type":"Snacks",
    "sales_channel":1,
    "order_priority":"C",
    "order_date":1346630400000,
    "order_id":531023156,
    "ship_date":"10\/15\/2012",
    "units_sold":407,
    "unit_price":152.58,
    "unit_cost":97.44,
    "total_revenue":62100.06,
    "total_cost":39658.08,
    "total_profit":22441.98,
    "shipping_address_id":34853,
    "street":"9899 Main St",
    "city":"Toronto",
    "state\/province":"ENG",
    "postal_code":43979.0,
    "phone_number":"Phone Number",
    "coupon_code":56265,
    "total_revenue_after_disc":43470.04,
    "total_profit_after_disc":15709.39,
    "days_since_purchase":4772
  },
  {
    "region":"Europe",
    "country":"Bulgaria",
    "item_type":"Clothes",
    "sales_channel":1,
    "order_priority":"L",
    "order_date":1282867200000,
    "order_id":880999934,
    "ship_date":"9\/16\/2010",
    "units_sold":6313,
    "unit_price":109.28,
    "unit_cost":35.84,
    "total_revenue":689884.64,
    "total_cost":226257.92,
    "total_profit":463626.72,
    "shipping_address_id":18721,
    "street":"4466 Main St",
    "city":"Berlin",
    "state\/province":"ON",
    "postal_code":90981.0,
    "phone_number":"Phone Number",
    "coupon_code":56265,
    "total_revenue_after_disc":482919.25,
    "total_profit_after_disc":324538.7,
    "days_since_purchase":5510
  },
  {
    "region":"Middle East and North Africa",
    "country":"Algeria",
    "item_type":"Personal Care",
    "sales_channel":1,
    "order_priority":"H",
    "order_date":1298160000000,
    "order_id":127468717,
    "ship_date":"3\/9\/2011",
    "units_sold":9681,
    "unit_price":81.73,
    "unit_cost":56.67,
    "total_revenue":791228.13,
    "total_cost":548622.27,
    "total_profit":242605.86,
    "shipping_address_id":54216,
    "street":"222 Main St",
    "city":"Toronto",
    "state\/province":"ENG",
    "postal_code":65107.0,
    "phone_number":"Phone Number",
    "coupon_code":86224,
    "total_revenue_after_disc":672543.91,
    "total_profit_after_disc":206214.98,
    "days_since_purchase":5333
  },
  {
    "region":"Asia",
    "country":"Mongolia",
    "item_type":"Clothes",
    "sales_channel":1,
    "order_priority":"L",
    "order_date":1449878400000,
    "order_id":770478332,
    "ship_date":"1\/24\/2016",
    "units_sold":515,
    "unit_price":109.28,
    "unit_cost":35.84,
    "total_revenue":56279.2,
    "total_cost":18457.6,
    "total_profit":37821.6,
    "shipping_address_id":83452,
    "street":"6899 Main St",
    "city":"Tokyo",
    "state\/province":"NY",
    "postal_code":11160.0,
    "phone_number":"Phone Number",
    "coupon_code":72705,
    "total_revenue_after_disc":39395.44,
    "total_profit_after_disc":26475.12,
    "days_since_purchase":3577
  },
  {
    "region":"Central America and the Caribbean",
    "country":"Grenada",
    "item_type":"Cereal",
    "sales_channel":1,
    "order_priority":"H",
    "order_date":1351382400000,
    "order_id":430390107,
    "ship_date":"11\/13\/2012",
    "units_sold":852,
    "unit_price":205.7,
    "unit_cost":117.11,
    "total_revenue":175256.4,
    "total_cost":99777.72,
    "total_profit":75478.68,
    "shipping_address_id":33064,
    "street":"9572 Main St",
    "city":"London",
    "state\/province":"TYO",
    "postal_code":97897.0,
    "phone_number":"Phone Number",
    "coupon_code":95341,
    "total_revenue_after_disc":140205.12,
    "total_profit_after_disc":60382.94,
    "days_since_purchase":4717
  },
  {
    "region":"Central America and the Caribbean",
    "country":"Grenada",
    "item_type":"Beverages",
    "sales_channel":1,
    "order_priority":"M",
    "order_date":1485734400000,
    "order_id":397877871,
    "ship_date":"3\/20\/2017",
    "units_sold":9759,
    "unit_price":47.45,
    "unit_cost":31.79,
    "total_revenue":463064.55,
    "total_cost":310238.61,
    "total_profit":152825.94,
    "shipping_address_id":61142,
    "street":"3827 Main St",
    "city":"Tokyo",
    "state\/province":"TYO",
    "postal_code":82577.0,
    "phone_number":"Phone Number",
    "coupon_code":98507,
    "total_revenue_after_disc":324145.18,
    "total_profit_after_disc":106978.16,
    "days_since_purchase":3162
  },
  {
    "region":"Sub-Saharan Africa",
    "country":"Senegal",
    "item_type":"Beverages",
    "sales_channel":0,
    "order_priority":"M",
    "order_date":1413936000000,
    "order_id":683927953,
    "ship_date":"11\/4\/2014",
    "units_sold":8334,
    "unit_price":47.45,
    "unit_cost":31.79,
    "total_revenue":395448.3,
    "total_cost":264937.86,
    "total_profit":130510.44,
    "shipping_address_id":48328,
    "street":"8550 Main St",
    "city":"London",
    "state\/province":"BE",
    "postal_code":94303.0,
    "phone_number":"Phone Number",
    "coupon_code":86224,
    "total_revenue_after_disc":336131.06,
    "total_profit_after_disc":110933.87,
    "days_since_purchase":3993
  },
  {
    "region":"North America",
    "country":"Greenland",
    "item_type":"Fruits",
    "sales_channel":0,
    "order_priority":"M",
    "order_date":1327968000000,
    "order_id":469839179,
    "ship_date":"2\/22\/2012",
    "units_sold":4709,
    "unit_price":9.33,
    "unit_cost":6.92,
    "total_revenue":43934.97,
    "total_cost":32586.28,
    "total_profit":11348.69,
    "shipping_address_id":90079,
    "street":"9239 Main St",
    "city":"Toronto",
    "state\/province":"NSW",
    "postal_code":20846.0,
    "phone_number":"Phone Number",
    "coupon_code":86224,
    "total_revenue_after_disc":37344.72,
    "total_profit_after_disc":9646.39,
    "days_since_purchase":4988
  },
  {
    "region":"Sub-Saharan Africa",
    "country":"Chad",
    "item_type":"Meat",
    "sales_channel":0,
    "order_priority":"H",

#### 12. Soft Interview Reflection - Markdown: < 120 words explaining how Functions have helped